modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/Rahala/SweetConcrete/issues" #optional

[[mods]]
modId="sweetconcrete"
version="1.14.4-1.4.0"
displayName="Sweet Concrete"
authors="Rahala" #optional
description='''
All the concrete blocks you can eat.
'''

[[dependencies.sweetconcrete]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
